# FILE: docker-compose.yml
version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tcd
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d tcd"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./vault/sql:/docker-entrypoint-initdb.d:ro

  otel-collector:
    image: otel/opentelemetry-collector:0.104.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4318:4318"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:13133/"]
      interval: 5s
      timeout: 3s
      retries: 10

  gateway:
    build: ./gateway
    environment:
      SIDE_URL: "http://sidecar:8081"
      PROVIDER_URL: "http://provider:8082"
      VAULT_URL: "http://vault:8083"
      GATEWAY_PORT: "8080"
      GATEWAY_SHARED_SECRET: "devshared"
      AUTH_JWT_SECRET: "devjwt"
      LOG_LEVEL: "INFO"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318/v1/traces"
      ASYNC_MODE: "0"
    ports: ["8080:8080"]
    depends_on:
      sidecar: { condition: service_healthy }
      provider: { condition: service_healthy }
      vault:    { condition: service_healthy }
      otel-collector: { condition: service_healthy }
    healthcheck:
      test: ["CMD","python","-c","import urllib.request; urllib.request.urlopen('http://localhost:8080/healthz', timeout=2)"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 8s
    restart: unless-stopped

  sidecar:
    build: ./sidecar
    environment:
      SIDECAR_PORT: "8081"
      LOG_LEVEL: "INFO"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318/v1/traces"
    ports: ["8081:8081"]
    healthcheck:
      test: ["CMD","python","-c","import urllib.request; urllib.request.urlopen('http://localhost:8081/healthz', timeout=2)"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  provider:
    build: ./provider
    environment:
      PROVIDER_PORT: "8082"
      LOG_LEVEL: "INFO"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318/v1/traces"
    ports: ["8082:8082"]
    healthcheck:
      test: ["CMD","python","-c","import urllib.request; urllib.request.urlopen('http://localhost:8082/healthz', timeout=2)"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  vault:
    build: ./vault
    environment:
      VAULT_PORT: "8083"
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/tcd"
      VAULT_SHARED_SECRET: "devshared"
      DEMO_ALLOW_UNSIGNED: "1"
      LOG_LEVEL: "INFO"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318/v1/traces"
    ports: ["8083:8083"]
    depends_on:
      postgres: { condition: service_healthy }
      otel-collector: { condition: service_healthy }
    healthcheck:
      test: ["CMD","python","-c","import urllib.request; urllib.request.urlopen('http://localhost:8083/healthz', timeout=2)"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped

volumes:
  pg_data: {}